### ISSUE TITLE
Import dump do pykota

### ISSUE THREAD

**Issue by thiagogomesverissimo** [uspdev/ansible-role-pykota#1]
```
      - name: copy the pykota mysql db
        copy:
          src: ../../files/pykota-mysql.sql
          dest: /tmp
        when: create_database_pykota.changed == True

      - name: import pykota-mysql.sql similar to mysql -u <username> -p <password> < hostname.sql
        mysql_db:
          state: import
          name: pykota
          target: /tmp/pykota-mysql.sql
        when: create_database_pykota.changed == True
```
